version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_HOST}:${OTEL_PORT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=${APP_NAME}
      OTEL_PROPAGATORS: tracecontext,baggage
    ports:
      - "8080:${API_PORT}"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:16.2
    hostname: pghost
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:${PG_PORT}"